name: client
description: "HS"
publish_to: 'none'
version: 0.0.2+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_math_fork: ^0.7.2
  flutter_riverpod: ^2.5.3
  flutter_hooks: ^0.20.5
  go_router: ^14.3.0
  json_serializable: ^6.8.0
  intl: ^0.19.0
  file_picker: ^8.1.3
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.3
  riverpod_annotation: ^2.5.3

flutter:

  uses-material-design: true

  assets:
    - assets/
